# Site settings
title: Yanxin(Peter) Peng
email: peterpen@usc.edu
description: > # keep this and put description below
  Game Programmer
url: "https://Peter00796.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/yanxin-peng-4456aa253/"
github_username: Peter00796
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
